### ISSUE TITLE
Student's grades table

### ISSUE THREAD

**Issue by mirametodieva** [SpasMilenkov/UniTrack#120]
# Feature Implementation: Student's grades and absences tables

### Objectives

- **Objective 1**: Develop a responsive and user-friendly student's grades table.
- **Objective 2**:  Implement a responsive student's absences table.

### Tasks

- [x] Task 1: Create the student's grades table component with columns for class name, grade, date, topic, teacherFirstName and teacherLastName.
- [x] Task 2: Add the student's absences table component with columns for subject, absence, excused, date, teacherFirstName and teacherLastName.
- [x] Task 3: Display the components in profile page

### Acceptance Criteria

- Criterion 1: Student's grades and absences tables should be visually appealing and easy to navigate.
