### ISSUE TITLE
User Profiles

### ISSUE THREAD

**Issue by mirametodieva** [SpasMilenkov/UniTrack#44]
# Feature Implementation: User Profiles

### Objectives

- **Objective 1**:  Design and implement a profile page for students, allowing them to review their details - profile picture, first and last name, class number, class name, grades, absences and upcoming events.
- **Objective 2**: Design and implement a profile page for teachers, providing them a platform to display their classes and upcoming events. Implement a possibility for adding grades, absences and events.

### Tasks

- [ ] Task 1: (Student & Teacher view) Create the UI design.
- [ ] Task 2: (Student view) Create the student profile page layout with sections for profile picture, first and last name, class number and class name.
- [ ] Task 3: (Student view) Implement UI design for grades and absences cards.
- [ ] Task 4: (Student & Teacher view) Create a component for upcoming event cards, displaying relevant information such as event title, description, date, creator and type.
- [ ] Task 5: (Teacher view) Develop a teacher profile page with sections for profile picture, classes, first and last name.
- [ ] Task 6: (Teacher view)  Implement the design for adding grades and absences.
- [ ] Task 7: (Teacher view) Create modals for adding grades, absences, and events.
- [ ] Task 8: (Student & Teacher view) Ensure responsive design to accommodate various screen sizes and devices.

### Acceptance Criteria

- Criterion 1: The student profile page should display profile picture, first and last name, class number and class name.
- Criterion 2: The student profile page should have UI design for grades and absences cards.
- Criterion 3: The upcoming event cards component should be available on both student and teacher views, showing relevant information.
- Criterion 4: The teacher profile page should display profile picture first and last name and classes.
- Criterion 5: The teacher profile page should have the possibility to add grades and absences.
- Criterion 6: Modals for adding grades, absences and events should be accessible to teachers.
- Criterion 7: The design should be responsive and accommodate various screen sizes and devices for both student and teacher views.
