### ISSUE TITLE
Students list page

### ISSUE THREAD

**Issue by mirametodieva** [SpasMilenkov/UniTrack#74]
# Feature Implementation: Students list page

### Objectives

- **Objective 1**: Implement students list page
- **Objective 2**: Add possibily to add grades and absences

### Tasks

- [ ] Task 1: Add students-list component
- [ ] Task 2:  Implement students list page's design
- [ ] Task 3:  Add dialogs components for adding grades and absences
- [ ] Task 4:  Add possibily for a teacher to add grades and absences
