### ISSUE TITLE
Recommended material card

### ISSUE THREAD

**Issue by mirametodieva** [SpasMilenkov/UniTrack#85]
# Feature Implementation: Recommended material card

### Objectives

- **Objective 1**: Design and implement a recommended material card.

### Tasks

- [ ] Task 1:  Design and Implement an attractive card.
- [ ] Task 2:  Dynamically populate card content.
- [ ] Task 3:  Add a responsive design.
