### ISSUE TITLE
Student's statistics page

### ISSUE THREAD

**Issue by mirametodieva** [SpasMilenkov/UniTrack#86]
# Feature Implementation: Student's statistics page

### Objectives

- **Objective 1**: : Design and implement a student's statistics page for a comprehensive view of academic performance.
- **Objective 2**:  Enhance user engagement by adding a section for recommended material cards.

### Tasks

- [x] Task 1: Design the student's statistics page.
- [x] Task 2: Implement the design in the application.
- [x] Task 3: Add a responsive design.
- [ ] Task4: Add a section for recommended material cards.
